### ISSUE TITLE
How are the letters represented in the rotations?

### ISSUE THREAD

**Issue by publicqi** [LionelOvaert/write-ups#1]
`the first rotation of the first video gives the letter {W}`
I do not understand how is W gave.

**Comment by LionelOvaert** [comment]
As you can see on this image (this is in fact the cube used for the challenge), the letters {U,W} are in the direction of rotation. (On my cube red and yellow are interchanged so that might be confusing but the mapping is correct) . 

If we had rotated the piece on the left, the letter Q would be in the good direction but X and T wouldn't have been in the good direction. I hope that's clear for you!
![image](https://user-images.githubusercontent.com/16003897/74072992-ff33cc80-4a08-11ea-9afb-c5fe762d1ab1.png)

**Comment by publicqi** [comment]
Got it. Thanks!
